apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: lumi-api
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 2
    max: 4
  liveness:
    path: /internal/isAlive
    initialDelay: 30
  readiness:
    path: /internal/isReady
    initialDelay: 30
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "1fac48f0-9744-4d44-a5b5-e2c8aa2ca42b" # team-esyfo
          - id: "7c0dd32a-1896-4e14-96f6-a7eadc73f5f5" # teamsykefravr
  accessPolicy:
    inbound:
      rules:
        - application: lumi-dashboard
        - application: bro-frontend
        - application: syfo-oppfolgingsplan-frontend
        - application: narmesteleder-frontend
        - application: dinesykmeldte
        - application: syfomodiaperson
          namespace: teamsykefravr
        - application: oppfolgingsplan-frontend
    outbound:
      external:
        - host: console.nav.cloud.nais.io
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-custom-1-3840
        diskAutoresize: true
        highAvailability: false
        flags:
          - name: "cloudsql.enable_pgaudit"
            value: "on"
          - name: "pgaudit.log"
            value: "write,ddl,role"
        databases:
          - name: lumi
            envVarPrefix: DB
  valkey:
    - instance: lumi-cache
      access: readwrite
  envFrom:
    - secret: nais-api-key
  env:
    - name: NAIS_CLUSTER_NAME
      value: prod-gcp
    - name: LUMI_DASHBOARD_CLIENT_ID
      value: prod-gcp:team-esyfo:lumi-dashboard
    - name: LUMI_TEAM_ENTRA_GROUPS
      value: team-esyfo=1fac48f0-9744-4d44-a5b5-e2c8aa2ca42b,teamsykefravr=7c0dd32a-1896-4e14-96f6-a7eadc73f5f5
    - name: NAIS_API_GRAPHQL_URL
      value: https://console.nav.cloud.nais.io/graphql
    - name: LUMI_CORS_ALLOWED_ORIGINS
      value: https://lumi-dashboard.ansatt.nav.no
