/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as ExportRouteImport } from './routes/export'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiInternalMetricsRouteImport } from './routes/api/internal/metrics'
import { Route as ApiInternalIsReadyRouteImport } from './routes/api/internal/isReady'
import { Route as ApiInternalIsAliveRouteImport } from './routes/api/internal/isAlive'

const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalMetricsRoute = ApiInternalMetricsRouteImport.update({
  id: '/api/internal/metrics',
  path: '/api/internal/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalIsReadyRoute = ApiInternalIsReadyRouteImport.update({
  id: '/api/internal/isReady',
  path: '/api/internal/isReady',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalIsAliveRoute = ApiInternalIsAliveRouteImport.update({
  id: '/api/internal/isAlive',
  path: '/api/internal/isAlive',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/export': typeof ExportRoute
  '/feedback': typeof FeedbackRoute
  '/api/internal/isAlive': typeof ApiInternalIsAliveRoute
  '/api/internal/isReady': typeof ApiInternalIsReadyRoute
  '/api/internal/metrics': typeof ApiInternalMetricsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/export': typeof ExportRoute
  '/feedback': typeof FeedbackRoute
  '/api/internal/isAlive': typeof ApiInternalIsAliveRoute
  '/api/internal/isReady': typeof ApiInternalIsReadyRoute
  '/api/internal/metrics': typeof ApiInternalMetricsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/export': typeof ExportRoute
  '/feedback': typeof FeedbackRoute
  '/api/internal/isAlive': typeof ApiInternalIsAliveRoute
  '/api/internal/isReady': typeof ApiInternalIsReadyRoute
  '/api/internal/metrics': typeof ApiInternalMetricsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/export'
    | '/feedback'
    | '/api/internal/isAlive'
    | '/api/internal/isReady'
    | '/api/internal/metrics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/export'
    | '/feedback'
    | '/api/internal/isAlive'
    | '/api/internal/isReady'
    | '/api/internal/metrics'
  id:
    | '__root__'
    | '/'
    | '/export'
    | '/feedback'
    | '/api/internal/isAlive'
    | '/api/internal/isReady'
    | '/api/internal/metrics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExportRoute: typeof ExportRoute
  FeedbackRoute: typeof FeedbackRoute
  ApiInternalIsAliveRoute: typeof ApiInternalIsAliveRoute
  ApiInternalIsReadyRoute: typeof ApiInternalIsReadyRoute
  ApiInternalMetricsRoute: typeof ApiInternalMetricsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/metrics': {
      id: '/api/internal/metrics'
      path: '/api/internal/metrics'
      fullPath: '/api/internal/metrics'
      preLoaderRoute: typeof ApiInternalMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/isReady': {
      id: '/api/internal/isReady'
      path: '/api/internal/isReady'
      fullPath: '/api/internal/isReady'
      preLoaderRoute: typeof ApiInternalIsReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/isAlive': {
      id: '/api/internal/isAlive'
      path: '/api/internal/isAlive'
      fullPath: '/api/internal/isAlive'
      preLoaderRoute: typeof ApiInternalIsAliveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExportRoute: ExportRoute,
  FeedbackRoute: FeedbackRoute,
  ApiInternalIsAliveRoute: ApiInternalIsAliveRoute,
  ApiInternalIsReadyRoute: ApiInternalIsReadyRoute,
  ApiInternalMetricsRoute: ApiInternalMetricsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
