/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SurveyverkstedRouteImport } from './routes/surveyverksted'
import { Route as SurveyPreviewRouteImport } from './routes/survey-preview'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as ExportRouteImport } from './routes/export'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SurveyverkstedIndexRouteImport } from './routes/surveyverksted.index'
import { Route as SurveyverkstedProjectIdRouteImport } from './routes/surveyverksted.$projectId'
import { Route as SurveyverkstedRevisionsRevisionIdRouteImport } from './routes/surveyverksted.revisions.$revisionId'
import { Route as ApiInternalMetricsRouteImport } from './routes/api/internal/metrics'
import { Route as ApiInternalIsReadyRouteImport } from './routes/api/internal/isReady'
import { Route as ApiInternalIsAliveRouteImport } from './routes/api/internal/isAlive'

const SurveyverkstedRoute = SurveyverkstedRouteImport.update({
  id: '/surveyverksted',
  path: '/surveyverksted',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyPreviewRoute = SurveyPreviewRouteImport.update({
  id: '/survey-preview',
  path: '/survey-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyverkstedIndexRoute = SurveyverkstedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SurveyverkstedRoute,
} as any)
const SurveyverkstedProjectIdRoute = SurveyverkstedProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => SurveyverkstedRoute,
} as any)
const SurveyverkstedRevisionsRevisionIdRoute =
  SurveyverkstedRevisionsRevisionIdRouteImport.update({
    id: '/revisions/$revisionId',
    path: '/revisions/$revisionId',
    getParentRoute: () => SurveyverkstedRoute,
  } as any)
const ApiInternalMetricsRoute = ApiInternalMetricsRouteImport.update({
  id: '/api/internal/metrics',
  path: '/api/internal/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalIsReadyRoute = ApiInternalIsReadyRouteImport.update({
  id: '/api/internal/isReady',
  path: '/api/internal/isReady',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalIsAliveRoute = ApiInternalIsAliveRouteImport.update({
  id: '/api/internal/isAlive',
  path: '/api/internal/isAlive',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/export': typeof ExportRoute
  '/feedback': typeof FeedbackRoute
  '/survey-preview': typeof SurveyPreviewRoute
  '/surveyverksted': typeof SurveyverkstedRouteWithChildren
  '/surveyverksted/$projectId': typeof SurveyverkstedProjectIdRoute
  '/surveyverksted/': typeof SurveyverkstedIndexRoute
  '/api/internal/isAlive': typeof ApiInternalIsAliveRoute
  '/api/internal/isReady': typeof ApiInternalIsReadyRoute
  '/api/internal/metrics': typeof ApiInternalMetricsRoute
  '/surveyverksted/revisions/$revisionId': typeof SurveyverkstedRevisionsRevisionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/export': typeof ExportRoute
  '/feedback': typeof FeedbackRoute
  '/survey-preview': typeof SurveyPreviewRoute
  '/surveyverksted/$projectId': typeof SurveyverkstedProjectIdRoute
  '/surveyverksted': typeof SurveyverkstedIndexRoute
  '/api/internal/isAlive': typeof ApiInternalIsAliveRoute
  '/api/internal/isReady': typeof ApiInternalIsReadyRoute
  '/api/internal/metrics': typeof ApiInternalMetricsRoute
  '/surveyverksted/revisions/$revisionId': typeof SurveyverkstedRevisionsRevisionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/export': typeof ExportRoute
  '/feedback': typeof FeedbackRoute
  '/survey-preview': typeof SurveyPreviewRoute
  '/surveyverksted': typeof SurveyverkstedRouteWithChildren
  '/surveyverksted/$projectId': typeof SurveyverkstedProjectIdRoute
  '/surveyverksted/': typeof SurveyverkstedIndexRoute
  '/api/internal/isAlive': typeof ApiInternalIsAliveRoute
  '/api/internal/isReady': typeof ApiInternalIsReadyRoute
  '/api/internal/metrics': typeof ApiInternalMetricsRoute
  '/surveyverksted/revisions/$revisionId': typeof SurveyverkstedRevisionsRevisionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/export'
    | '/feedback'
    | '/survey-preview'
    | '/surveyverksted'
    | '/surveyverksted/$projectId'
    | '/surveyverksted/'
    | '/api/internal/isAlive'
    | '/api/internal/isReady'
    | '/api/internal/metrics'
    | '/surveyverksted/revisions/$revisionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/export'
    | '/feedback'
    | '/survey-preview'
    | '/surveyverksted/$projectId'
    | '/surveyverksted'
    | '/api/internal/isAlive'
    | '/api/internal/isReady'
    | '/api/internal/metrics'
    | '/surveyverksted/revisions/$revisionId'
  id:
    | '__root__'
    | '/'
    | '/export'
    | '/feedback'
    | '/survey-preview'
    | '/surveyverksted'
    | '/surveyverksted/$projectId'
    | '/surveyverksted/'
    | '/api/internal/isAlive'
    | '/api/internal/isReady'
    | '/api/internal/metrics'
    | '/surveyverksted/revisions/$revisionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExportRoute: typeof ExportRoute
  FeedbackRoute: typeof FeedbackRoute
  SurveyPreviewRoute: typeof SurveyPreviewRoute
  SurveyverkstedRoute: typeof SurveyverkstedRouteWithChildren
  ApiInternalIsAliveRoute: typeof ApiInternalIsAliveRoute
  ApiInternalIsReadyRoute: typeof ApiInternalIsReadyRoute
  ApiInternalMetricsRoute: typeof ApiInternalMetricsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/surveyverksted': {
      id: '/surveyverksted'
      path: '/surveyverksted'
      fullPath: '/surveyverksted'
      preLoaderRoute: typeof SurveyverkstedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey-preview': {
      id: '/survey-preview'
      path: '/survey-preview'
      fullPath: '/survey-preview'
      preLoaderRoute: typeof SurveyPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveyverksted/': {
      id: '/surveyverksted/'
      path: '/'
      fullPath: '/surveyverksted/'
      preLoaderRoute: typeof SurveyverkstedIndexRouteImport
      parentRoute: typeof SurveyverkstedRoute
    }
    '/surveyverksted/$projectId': {
      id: '/surveyverksted/$projectId'
      path: '/$projectId'
      fullPath: '/surveyverksted/$projectId'
      preLoaderRoute: typeof SurveyverkstedProjectIdRouteImport
      parentRoute: typeof SurveyverkstedRoute
    }
    '/surveyverksted/revisions/$revisionId': {
      id: '/surveyverksted/revisions/$revisionId'
      path: '/revisions/$revisionId'
      fullPath: '/surveyverksted/revisions/$revisionId'
      preLoaderRoute: typeof SurveyverkstedRevisionsRevisionIdRouteImport
      parentRoute: typeof SurveyverkstedRoute
    }
    '/api/internal/metrics': {
      id: '/api/internal/metrics'
      path: '/api/internal/metrics'
      fullPath: '/api/internal/metrics'
      preLoaderRoute: typeof ApiInternalMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/isReady': {
      id: '/api/internal/isReady'
      path: '/api/internal/isReady'
      fullPath: '/api/internal/isReady'
      preLoaderRoute: typeof ApiInternalIsReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/isAlive': {
      id: '/api/internal/isAlive'
      path: '/api/internal/isAlive'
      fullPath: '/api/internal/isAlive'
      preLoaderRoute: typeof ApiInternalIsAliveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SurveyverkstedRouteChildren {
  SurveyverkstedProjectIdRoute: typeof SurveyverkstedProjectIdRoute
  SurveyverkstedIndexRoute: typeof SurveyverkstedIndexRoute
  SurveyverkstedRevisionsRevisionIdRoute: typeof SurveyverkstedRevisionsRevisionIdRoute
}

const SurveyverkstedRouteChildren: SurveyverkstedRouteChildren = {
  SurveyverkstedProjectIdRoute: SurveyverkstedProjectIdRoute,
  SurveyverkstedIndexRoute: SurveyverkstedIndexRoute,
  SurveyverkstedRevisionsRevisionIdRoute:
    SurveyverkstedRevisionsRevisionIdRoute,
}

const SurveyverkstedRouteWithChildren = SurveyverkstedRoute._addFileChildren(
  SurveyverkstedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExportRoute: ExportRoute,
  FeedbackRoute: FeedbackRoute,
  SurveyPreviewRoute: SurveyPreviewRoute,
  SurveyverkstedRoute: SurveyverkstedRouteWithChildren,
  ApiInternalIsAliveRoute: ApiInternalIsAliveRoute,
  ApiInternalIsReadyRoute: ApiInternalIsReadyRoute,
  ApiInternalMetricsRoute: ApiInternalMetricsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
