name: Deploy Submission Proxy

on:
  push:
    branches:
      - main
    paths:
      - 'apps/lumi-submission-proxy/**'
      # Workflow-filen selv — behold denne permanent slik at endringer i workflowen også trigger deploy
      - '.github/workflows/deploy-proxy.yaml'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          cache-overwrite-existing: true

      - name: Build with Gradle
        working-directory: apps/lumi-submission-proxy
        run: ./gradlew build

      - name: Push docker image to GAR
        uses: nais/docker-build-push@be85229e81c0293c265c646c084f05317fb6e0d2
        id: docker-build-push
        with:
          team: team-esyfo
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          dockerfile: apps/lumi-submission-proxy/Dockerfile
          docker_context: apps/lumi-submission-proxy
          image_suffix: submission-proxy
          push_image: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

  deploy-dev:
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: nais/deploy/actions/deploy@2f28259ff29ea37915f5a0c9e2a8e3542c429df7
        env:
          CLUSTER: dev-gcp
          RESOURCE: apps/lumi-submission-proxy/nais/dev.yaml
          VAR: image=${{ needs.build.outputs.image }}
