name: Deploy Submission Proxy

on:
  push:
    branches:
      - main
    paths:
      - 'apps/lumi-submission-proxy/**'
      # Workflow-filen selv — behold denne permanent slik at endringer i workflowen også trigger deploy
      - '.github/workflows/deploy-proxy.yaml'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Setup Java
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          cache-overwrite-existing: true

      - name: Build with Gradle
        working-directory: apps/lumi-submission-proxy
        run: ./gradlew build

      - name: Push docker image to GAR
        uses: nais/docker-build-push@2d2b0a7193e65422b7f0355d4afb445e0a8b2cc3
        id: docker-build-push
        with:
          team: team-esyfo
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          dockerfile: apps/lumi-submission-proxy/Dockerfile
          docker_context: apps/lumi-submission-proxy
          image_suffix: submission-proxy
          push_image: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

  deploy-dev:
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: nais/deploy/actions/deploy@fc3eae3edebabdf67f7592102ae16176d5ba3b5f
        env:
          CLUSTER: dev-gcp
          RESOURCE: apps/lumi-submission-proxy/nais/dev.yaml
          VAR: image=${{ needs.build.outputs.image }}
