name: Deploy API

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      target:
        description: Where to deploy
        type: choice
        required: true
        options:
          - dev
          - prod
      ref:
        description: Git ref to deploy (branch/tag/sha). Defaults to the ref you run the workflow from.
        type: string
        required: false

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          ref: ${{ inputs.ref || github.ref }}

      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@5e2ebd065dc2488b7a6ad670704656cbbe1e8f60
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          cache-overwrite-existing: true

      - name: Build with Gradle
        working-directory: apps/lumi-api
        run: ./gradlew shadowJar

      - name: Push docker image to GAR
        uses: nais/docker-build-push@05dbb6091b30bd84279c6d64a45ef8782fd410a5
        id: docker-build-push
        with:
          team: team-esyfo
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          dockerfile: apps/lumi-api/Dockerfile
          docker_context: apps/lumi-api
          image_suffix: api
          push_image: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

  deploy-dev:
    if: |
      github.ref == 'refs/heads/main' ||
      (github.event_name == 'workflow_dispatch' && inputs.target == 'dev')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - uses: nais/deploy/actions/deploy@a7f8690f9b367fcbf5348a0a1e21d44f1aae50eb
        env:
          CLUSTER: dev-gcp
          RESOURCE: apps/lumi-api/nais/app/dev.yaml
          VAR: image=${{ needs.build.outputs.image }}

  deploy-prod:
    if: |
      github.ref == 'refs/heads/main' ||
      (github.event_name == 'workflow_dispatch' && inputs.target == 'prod')
    needs: [build, deploy-dev]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - uses: nais/deploy/actions/deploy@a7f8690f9b367fcbf5348a0a1e21d44f1aae50eb
        env:
          CLUSTER: prod-gcp
          RESOURCE: apps/lumi-api/nais/app/prod.yaml
          VAR: image=${{ needs.build.outputs.image }}
